var bg_top = {
	"battle-chateau-baron": {
		"name": "Battle Chateau Baron",
		"url": "battle-chateau-baron.png",
		"url_mini": "battle-chateau-baron-mini.png",
		"overlay": "d5.png",
	},
	"battle-chateau-baroness": {
		"name": "Battle Chateau Baroness",
		"url": "battle-chateau-baroness.png",
		"url_mini": "battle-chateau-baroness-mini.png",
		"overlay": "d5.png",
	},
	"battle-chateau-viscount": {
		"name": "Battle Chateau Viscount",
		"url": "battle-chateau-viscount.png",
		"url_mini": "battle-chateau-viscount-mini.png",
		"overlay": "d5.png",
	},
	"battle-chateau-viscountess": {
		"name": "Battle Chateau Viscountess",
		"url": "battle-chateau-viscountess.png",
		"url_mini": "battle-chateau-viscountess-mini.png",
		"overlay": "d5.png",
	},
	"battle-chateau-earl": {
		"name": "Battle Chateau Earl",
		"url": "battle-chateau-earl.png",
		"url_mini": "battle-chateau-earl-mini.png",
		"overlay": "d5.png",
	},
	"battle-chateau-countess": {
		"name": "Battle Chateau Countess",
		"url": "battle-chateau-countess.png",
		"url_mini": "battle-chateau-countess-mini.png",
		"overlay": "d5.png",
	},
	"battle-chateau-marquis": {
		"name": "Battle Chateau Marquis",
		"url": "battle-chateau-marquis.png",
		"url_mini": "battle-chateau-marquis-mini.png",
		"overlay": "d5.png",
	},
	"battle-chateau-marchioness": {
		"name": "Battle Chateau Marchioness",
		"url": "battle-chateau-marchioness.png",
		"url_mini": "battle-chateau-marchioness-mini.png",
		"overlay": "d5.png",
	},
	"battle-chateau-duke": {
		"name": "Battle Chateau Duke",
		"url": "battle-chateau-duke.png",
		"url_mini": "battle-chateau-duke-mini.png",
		"overlay": "d5.png",
	},
	"battle-chateau-duchess": {
		"name": "Battle Chateau Duchess",
		"url": "battle-chateau-duchess.png",
		"url_mini": "battle-chateau-duchess-mini.png",
		"overlay": "d5.png",
	},
	"battle-chateau-grand-duke": {
		"name": "Battle Chateau Grand Duke",
		"url": "battle-chateau-grand-duke.png",
		"url_mini": "battle-chateau-grand-duke-mini.png",
		"overlay": "d5.png",
	},
	"battle-chateau-grand-duchess": {
		"name": "Battle Chateau Grand Duchess",
		"url": "battle-chateau-grand-duchess.png",
		"url_mini": "battle-chateau-grand-duchess-mini.png",
		"overlay": "d5.png",
	},
	"t1": {
		"name": "default 01",
		"url": "t1.png",
		"url_mini": "t1-mini.png",
		"overlay": "d1.png",
	},
	"t2": {
		"name": "default 02 - Hard Mode",
		"url": "t2.png",
		"url_mini": "t2-mini.png",
		"overlay": "d1.png",
	},
	"t3": {
		"name": "frontier default 01",
		"url": "t3.png",
		"url_mini": "t3-mini.png",
		"overlay": "d2.png",
	},
	"t4": {
		"name": "SS5 default 01",
		"url": "t4.png",
		"url_mini": "t4-mini.png",
		"overlay": "d2.png",
	},
	"t5": {
		"name": "SS6 default 01",
		"url": "t5.png",
		"url_mini": "t5-mini.png",
		"overlay": "d2.png",
	},
	"t6": {
		"name": "Wifi battle bg",
		"url": "t6.png",
		"url_mini": "t6-mini.png",
		"overlay": "d2.png",
	},
	"t7": {
		"name": "Victory road battle bg",
		"url": "t7.png",
		"url_mini": "t7-mini.png",
		"overlay": "d2.png",
	},
	"trophy": {
		"name": "Champion trophy",
		"url": "trophy.png",
		"url_mini": "trophy-mini.png",
		"overlay": "d2.png",
	},
	"medal": {
		"name": "Champion medal",
		"url": "medal.png",
		"url_mini": "medal-mini.png",
		"overlay": "d2.png",
	},
	// "mono-bug": {
	// 	"name": "Mono type - Bug",
	// 	"url": "mono-bug.png",
	// 	"url_mini": "mono-bug-mini.png",
	// 	"overlay": "d2.png",
	// },
	"mono-dark": {
		"name": "Mono type - Dark",
		"url": "mono-dark.png",
		"url_mini": "mono-dark-mini.png",
		"overlay": "d2.png",
	},
	"mono-dragon": {
		"name": "Mono type - Dragon",
		"url": "mono-dragon.png",
		"url_mini": "mono-dragon-mini.png",
		"overlay": "d2.png",
	},
	"mono-electric": {
		"name": "Mono type - Electric",
		"url": "mono-electric.png",
		"url_mini": "mono-electric-mini.png",
		"overlay": "d2.png",
	},
	"mono-fairy": {
		"name": "Mono type - Fairy",
		"url": "mono-fairy.png",
		"url_mini": "mono-fairy-mini.png",
		"overlay": "d2.png",
	},
	// "mono-fighting": {
	// 	"name": "Mono type - Fighting",
	// 	"url": "mono-fighting.png",
	// 	"url_mini": "mono-fighting-mini.png",
	// 	"overlay": "d2.png",
	// },
	// "mono-fire": {
	// 	"name": "Mono type - Fire",
	// 	"url": "mono-fire.png",
	// 	"url_mini": "mono-fire-mini.png",
	// 	"overlay": "d2.png",
	// },
	"mono-flying": {
		"name": "Mono type - Flying",
		"url": "mono-flying.png",
		"url_mini": "mono-flying-mini.png",
		"overlay": "d2.png",
	},
	// "mono-ghost": {
	// 	"name": "Mono type - Ghost",
	// 	"url": "mono-ghost.png",
	// 	"url_mini": "mono-ghost-mini.png",
	// 	"overlay": "d2.png",
	// },
	// "mono-grass": {
	// 	"name": "Mono type - Grass",
	// 	"url": "mono-grass.png",
	// 	"url_mini": "mono-grass-mini.png",
	// 	"overlay": "d2.png",
	// },
	"mono-ground": {
		"name": "Mono type - Ground",
		"url": "mono-ground.png",
		"url_mini": "mono-ground-mini.png",
		"overlay": "d2.png",
	},
	// "mono-ice": {
	// 	"name": "Mono type - Ice",
	// 	"url": "mono-ice.png",
	// 	"url_mini": "mono-ice-mini.png",
	// 	"overlay": "d2.png",
	// },
	// "mono-normal": {
	// 	"name": "Mono type - Normal",
	// 	"url": "mono-normal.png",
	// 	"url_mini": "mono-normal-mini.png",
	// 	"overlay": "d2.png",
	// },
	// "mono-poison": {
	// 	"name": "Mono type - Poison",
	// 	"url": "mono-poison.png",
	// 	"url_mini": "mono-poison-mini.png",
	// 	"overlay": "d2.png",
	// },
	"mono-psychic": {
		"name": "Mono type - Psychic",
		"url": "mono-psychic.png",
		"url_mini": "mono-psychic-mini.png",
		"overlay": "d2.png",
	},
	// "mono-rock": {
	// 	"name": "Mono type - Rock",
	// 	"url": "mono-rock.png",
	// 	"url_mini": "mono-rock-mini.png",
	// 	"overlay": "d2.png",
	// },
	"mono-steel": {
		"name": "Mono type - Steel",
		"url": "mono-steel.png",
		"url_mini": "mono-steel-mini.png",
		"overlay": "d2.png",
	},
	// "mono-water": {
	// 	"name": "Mono type - Water",
	// 	"url": "mono-water.png",
	// 	"url_mini": "mono-water-mini.png",
	// 	"overlay": "d2.png",
	// },
}

var bg_bottom = {
	"b1": {
		"name": "default 01",
		"url": "b1.png",
		"url_mini": "b1-mini.png",
	},
	"b2": {
		"name": "default 02 - Hard Mode",
		"url": "b2.png",
		"url_mini": "b2-mini.png",
	},
	"b3": {
		"name": "frontier default 01",
		"url": "b3.png",
		"url_mini": "b3-mini.png",
	},
	"b4": {
		"name": "SS5 default 01",
		"url": "b4.png",
		"url_mini": "b4-mini.png",
	},
	"b5": {
		"name": "SS6 default 01",
		"url": "b5.png",
		"url_mini": "b5-mini.png",
	},
	// "b0": {
	// 	"name": "no bottom card",
	// 	"url": "b0-mini.png",
	// 	"url_mini": "b0-mini.png",
	// },
}