var varient = {
	"003": {
		"n": 'Venusaur',
		"m": 'Mega Venusaur',
	},
	"006": {
		"n": 'Charizard',
		"x": 'Mega Charizard X',
		"y": 'Mega Charizard Y',
	},
	"009": {
		"n": 'Blastoise',
		"m": 'Mega Blastoise',
	},
	"015": {
		"n": 'Beedrill',
		"m": 'Mega Beedrill',
	},
	"018": {
		"n": 'Pidgeot',
		"m": 'Mega Pidgeot',
	},
	"025": {
		"n": 'Pikachu',
		"c": 'Cosplay Pikachu',
		"b": 'Belle Pikachu',
		"l": 'Libre Pikachu',
		"d": 'Ph.D. Pikachu',
		"p": 'Pop Star Pikachu',
		"r": 'Rock Star Pikachu',
	},
	"065": {
		"n": 'Alakazam',
		"m": 'Mega Alakazam',
	},
	"080": {
		"n": 'Slowbro',
		"m": 'Mega Slowbro',
	},
	"094": {
		"n": 'Gengar',
		"m": 'Mega Gengar',
	},
	"115": {
		"n": 'Kangaskhan',
		"m": 'Mega Kangaskhan',
	},
	"127": {
		"n": 'Pinsir',
		"m": 'Mega Pinsir',
	},
	"130": {
		"n": 'Gyarados',
		"m": 'Mega Gyarados',
	},
	"142": {
		"n": 'Aerodactyl',
		"m": 'Mega Aerodactyl',
	},
	"150": {
		"n": 'Mewtwo',
		"x": 'Mega Mewtwo X',
		"y": 'Mega Mewtwo Y',
	},
	"181": {
		"n": 'Ampharos',
		"m": 'Mega Ampharos',
	},
	"201": {
		"a": 'A Unown',
		"b": 'B Unown',
		"c": 'C Unown',
		"d": 'D Unown',
		"e": 'E Unown',
		"f": 'F Unown',
		"g": 'G Unown',
		"h": 'H Unown',
		"i": 'I Unown',
		"j": 'J Unown',
		"k": 'K Unown',
		"l": 'L Unown',
		"m": 'M Unown',
		"n": 'N Unown',
		"o": 'O Unown',
		"p": 'P Unown',
		"q": 'Q Unown',
		"r": 'R Unown',
		"s": 'S Unown',
		"t": 'T Unown',
		"u": 'U Unown',
		"v": 'V Unown',
		"w": 'W Unown',
		"x": 'X Unown',
		"y": 'Y Unown',
		"z": 'Z Unown',
		"!": '! Unown',
		"?": '? Unown',
	},
	"208": {
		"n": 'Steelix',
		"m": 'Mega Steelix',
	},
	"212": {
		"n": 'Scizor',
		"m": 'Mega Scizor',
	},
	"214": {
		"n": 'Heracross',
		"m": 'Mega Heracross',
	},
	"229": {
		"n": 'Houndoom',
		"m": 'Mega Houndoom',
	},
	"248": {
		"n": 'Tyranitar',
		"m": 'Mega Tyranitar',
	},
	"254": {
		"n": 'Sceptile',
		"m": 'Mega Sceptile',
	},
	"257": {
		"n": 'Blaziken',
		"m": 'Mega Blaziken',
	},
	"260": {
		"n": 'Swampert',
		"m": 'Mega Swampert',
	},
	"282": {
		"n": 'Gardevoir',
		"m": 'Mega Gardevoir',
	},
	"302": {
		"n": 'Sableye',
		"m": 'Mega Sableye',
	},
	"303": {
		"n": 'Mawile',
		"m": 'Mega Mawile',
	},
	"306": {
		"n": 'Aggron',
		"m": 'Mega Aggron',
	},
	"308": {
		"n": 'Medicham',
		"m": 'Mega Medicham',
	},
	"310": {
		"n": 'Manetric',
		"m": 'Mega Manetric',
	},
	"319": {
		"n": 'Sharpedo',
		"m": 'Mega Sharpedo',
	},
	"323": {
		"n": 'Camerupt',
		"m": 'Mega Camerupt',
	},
	"334": {
		"n": 'Altaria',
		"m": 'Mega Altaria',
	},
	"351": {
		"n": 'Castform',
		"r": 'Rainy Form Castform',
		"h": 'Snowy Form Castform',
		"s": 'Sunny Form Castform',
	},
	"354": {
		"n": 'Banette',
		"m": 'Mega Banette',
	},
	"359": {
		"n": 'Absol',
		"m": 'Mega Absol',
	},
	"362": {
		"n": 'Glalie',
		"m": 'Mega Glalie',
	},
	"373": {
		"n": 'Salamence',
		"m": 'Mega Salamence',
	},
	"376": {
		"n": 'Metagross',
		"m": 'Mega Metagross',
	},
	"380": {
		"n": 'Latias',
		"m": 'Mega Latias',
	},
	"381": {
		"n": 'Latios',
		"m": 'Mega Latios',
	},
	"382": {
		"n": 'Kyogre',
		"p": 'Primal Kyogre',
	},
	"383": {
		"n": 'Groudon',
		"p": 'Primal Groudon',
	},
	"384": {
		"n": 'Rayquaza',
		"m": 'Mega Rayquaza',
	},
	"386": {
		"n": 'Normal Forme Deoxys',
		"a": 'Attack Forme Deoxys',
		"d": 'Defense Forme Deoxys',
		"s": 'Speed Forme Deoxys',
	},
	"412": {
		"p": 'Plant Cloak Burmy',
		"s": 'Sandy Cloak Burmy',
		"t": 'Trash Cloak Burmy',
	},
	"413": {
		"p": 'Plant Cloak Wormadam',
		"s": 'Sandy Cloak Wormadam',
		"t": 'Trash Cloak Wormadam',
	},
	"421": {
		"o": 'Overcast Form Cherrim',
		"s": 'Sunshine Form Cherrim',
	},
	"422": {
		"e": 'East Sea Shellos',
		"w": 'West Sea Shellos',
	},
	"423": {
		"e": 'East Sea Gastrodon',
		"w": 'West Sea Gastrodon',
	},
	"428": {
		"n": 'Lopunny',
		"m": 'Mega Lopunny',
	},
	"445": {
		"n": 'Garchomp',
		"m": 'Mega Garchomp',
	},
	"448": {
		"n": 'Lucario',
		"m": 'Mega Lucario',
	},
	"460": {
		"n": 'Abomasnow',
		"m": 'Mega Abomasnow',
	},
	"475": {
		"n": 'Gallade',
		"m": 'Mega Gallade',
	},
	"479": {
		"n": 'Rotom',
		"y": 'Fan Rotom',
		"i": 'Frost Rotom',
		"f": 'Heat Rotom',
		"g": 'Mow Rotom',
		"w": 'Wash Rotom',
	},
	"487": {
		"a": 'Altered Forme Giratina',
		"o": 'Origin Forme Giratina',
	},
	"492": {
		"l": 'Land Forme Shaymin',
		"s": 'Sky Forme Shaymin',
	},
	"493": {
		"n": 'Normal Arceus',
		"f": 'Fire Arceus',
		"w": 'Water Arceus',
		"e": 'Electric Arceus',
		"g": 'Grass Arceus',
		"i": 'Ice Arceus',
		"h": 'Fighting Arceus',
		"p": 'Poison Arceus',
		"u": 'Ground Arceus',
		"y": 'Flying Arceus',
		"c": 'Psychic Arceus',
		"b": 'Bug Arceus',
		"o": 'Rock Arceus',
		"s": 'Ghost Arceus',
		"d": 'Dragon Arceus',
		"k": 'Dark Arceus',
		"l": 'Steel Arceus',
		"r": 'Fairy Arceus',
	},
	"531": {
		"n": 'Audino',
		"m": 'Mega Audino',
	},
	"550": {
		"b": 'Blue Stripe Basculin',
		"r": 'Red Stripe Basculin'
	},
	"555": {
		"s": 'Standard Mode Darmanitan',
		"z": 'Zen Mode Darmanitan',
	},
	"585": {
		"p": 'Spring Form Deerling',
		"m": 'Summer Form Deerling',
		"a": 'Autumn Form Deerling',
		"w": 'Winter Form Deerling',
	},
	"586": {
		"p": 'Spring Form Sawbuck',
		"m": 'Summer Form Sawbuck',
		"a": 'Autumn Form Sawbuck',
		"w": 'Winter Form Sawbuck',
	},
	"641": {
		"i": 'Incarnate Forme Tornadus',
		"t": 'Therian Forme Tornadus',
	},
	"642": {
		"i": 'Incarnate Forme Thundurus',
		"t": 'Therian Forme Thundurus',
	},
	"645": {
		"i": 'Incarnate Forme Landorus',
		"t": 'Therian Forme Landorus',
	},
	"646": {
		"n": 'Kyurem',
		"b": 'Black Kyurem',
		"w": 'White Kyurem',
	},
	"647": {
		"o": 'Ordinary Form Keldeo',
		"r": 'Resolute Form Keldeo',
	},
	"648": {
		"a": 'Aria Forme Meloetta',
		"p": 'Pirouette Forme Meloetta',
	},
	"649": {
		"n": 'Genesect',
		"e": 'Shock Drive Genesect',
		"f": 'Burn Drive Genesect',
		"i": 'Chill Drive Genesect',
		"w": 'Douse Drive Genesect',
	},
	"666": {
		"m": 'Meadow Pattern Vivillon',
		"a": 'Archipelago Pattern Vivillon',
		"c": 'Continental Pattern Vivillon',
		"e": 'Elegant Pattern Vivillon',
		"f ": 'Fancy Pattern Vivillon',
		"g": 'Garden Pattern Vivillon',
		"h": 'High Plains Pattern Vivillon',
		"i": 'Icy Snow Pattern Vivillon',
		"j": 'Jungle Pattern Vivillon',
		"n": 'Marine Pattern Vivillon',
		"d": 'Modern Pattern Vivillon',
		"x": 'Monsoon Pattern Vivillon',
		"o": 'Ocean Pattern Vivillon',
		"p": 'Poke Ball Pattern Vivillon',
		"l": 'Polar Pattern Vivillon',
		"r": 'River Pattern Vivillon',
		"s": 'Sandstorm Pattern Vivillon',
		"v": 'Savanna Pattern Vivillon',
		"u": 'Sun Pattern Vivillon',
		"t": 'Tundra Pattern Vivillon',
	},
	"669": {
		"r": 'Red Flower Flabebe',
		"y": 'Yellow Flower Flabebe',
		"o": 'Orange Flower Flabebe',
		"b": 'Blue Flower Flabebe',
		"w": 'White Flower Flabebe',
	},
	"670": {
		"r": 'Red Flower Floette',
		"y": 'Yellow Flower Floette',
		"o": 'Orange Flower Floette',
		"b": 'Blue Flower Floette',
		"w": 'White Flower Floette',
		"e": 'Eternal Flower Floette',
	},
	"671": {
		"r": 'Red Flower Florges',
		"y": 'Yellow Flower Florges',
		"o": 'Orange Flower Florges',
		"b": 'Blue Flower Florges',
		"w": 'White Flower Florges',
	},
	"676": {
		"n": 'Natural Form Furfrou',
		"d": 'Dandy Trim Furfrou',
		"b": 'Debutante Trim Furfrou',
		"o": 'Diamond Trim Furfrou',
		"h": 'Heart Trim Furfrou',
		"k": 'Kabuki Trim Furfrou',
		"l": 'La Reine Trim Furfrou',
		"m": 'Matron Trim Furfrou',
		"p": 'Pharaoh Trim Furfrou',
		"s": 'Star Trim Furfrou',
	},
	"681": {
		"s": 'Shield Forme Aegislash',
		"b": 'Blade Forme Aegislash',
	},
	"710": {
		"m": 'Average Size Pumpkaboo',
		"s": 'Small Size Pumpkaboo',
		"l": 'Large Size Pumpkaboo',
		"x": 'Super Size Pumpkaboo',
	},
	"711": {
		"m": 'Average Size Gourgeist',
		"s": 'Small Size Gourgeist',
		"l": 'Large Size Gourgeist',
		"x": 'Super Size Gourgeist',
	},
	"716": {
		"a": 'Active Mode Xerneas',
		"n": 'Neutral Mode Xerneas',
	},
	"719": {
		"n": 'Diancie',
		"m": 'Mega Diancie',
	},
	"720": {
		"c": 'Hoopa Confined',
		"u": 'Unbound Confined',
	},
}