var varient = {
	003: {
		n: 'Venusaur',
		m: 'Mega Venusaur',
	},
	006: {
		n: 'Charizard',
		mx: 'Mega Charizard X',
		my: 'Mega Charizard Y',
	},
	009: {
		n: 'Blastoise',
		m: 'Mega Blastoise',
	},
	015: {
		n: 'Beedrill',
		m: 'Mega Beedrill',
	},
	018: {
		n: 'Pidgeot',
		m: 'Mega Pidgeot',
	},
	025: {
		n: 'Pikachu',
		cosplay: 'Cosplay Pikachu',
		belle: 'Belle Pikachu',
		libre: 'Libre Pikachu',
		phd: 'Ph.D. Pikachu',
		popstar: 'Pop Star Pikachu',
		rockstar: 'Rock Star Pikachu',
	},
	065: {
		n: 'Alakazam',
		m: 'Mega Alakazam',
	},
	080: {
		n: 'Slowbro',
		m: 'Mega Slowbro',
	},
	094: {
		n: 'Gengar',
		m: 'Mega Gengar',
	},
	115: {
		n: 'Kangaskhan',
		m: 'Mega Kangaskhan',
	},
	127: {
		n: 'Pinsir',
		m: 'Mega Pinsir',
	},
	130: {
		n: 'Gyarados',
		m: 'Mega Gyarados',
	},
	142: {
		n: 'Aerodactyl',
		m: 'Mega Aerodactyl',
	},
	150: {
		n: 'Mewtwo',
		mx: 'Mega Mewtwo X',
		my: 'Mega Mewtwo Y',
	},
	181: {
		n: 'Ampharos',
		m: 'Mega Ampharos',
	},
	201: {
		a: 'A Unown',
		b: 'B Unown',
		c: 'C Unown',
		d: 'D Unown',
		e: 'E Unown',
		f: 'F Unown',
		g: 'G Unown',
		h: 'H Unown',
		i: 'I Unown',
		j: 'J Unown',
		k: 'K Unown',
		l: 'L Unown',
		m: 'M Unown',
		n: 'N Unown',
		o: 'O Unown',
		p: 'P Unown',
		q: 'Q Unown',
		r: 'R Unown',
		s: 'S Unown',
		t: 'T Unown',
		u: 'U Unown',
		v: 'V Unown',
		w: 'W Unown',
		x: 'X Unown',
		y: 'Y Unown',
		z: 'Z Unown',
		exclamation: '! Unown',
		question: '? Unown',
	},
	208: {
		n: 'Steelix',
		m: 'Mega Steelix',
	},
	212: {
		n: 'Scizor',
		m: 'Mega Scizor',
	},
	214: {
		n: 'Heracross',
		m: 'Mega Heracross',
	},
	229: {
		n: 'Houndoom',
		m: 'Mega Houndoom',
	},
	248: {
		n: 'Tyranitar',
		m: 'Mega Tyranitar',
	},
	254: {
		n: 'Sceptile',
		m: 'Mega Sceptile',
	},
	257: {
		n: 'Blaziken',
		m: 'Mega Blaziken',
	},
	260: {
		n: 'Swampert',
		m: 'Mega Swampert',
	},
	282: {
		n: 'Gardevoir',
		m: 'Mega Gardevoir',
	},
	302: {
		n: 'Sableye',
		m: 'Mega Sableye',
	},
	303: {
		n: 'Mawile',
		m: 'Mega Mawile',
	},
	306: {
		n: 'Aggron',
		m: 'Mega Aggron',
	},
	308: {
		n: 'Medicham',
		m: 'Mega Medicham',
	},
	310: {
		n: 'Manetric',
		m: 'Mega Manetric',
	},
	319: {
		n: 'Sharpedo',
		m: 'Mega Sharpedo',
	},
	323: {
		n: 'Camerupt',
		m: 'Mega Camerupt',
	},
	334: {
		n: 'Altaria',
		m: 'Mega Altaria',
	},
	351: {
		n: 'Castform',
		rainy: 'Rainy Form Castform',
		snowy: 'Snowy Form Castform',
		sunny: 'Sunny Form Castform',
	},
	354: {
		n: 'Banette',
		m: 'Mega Banette',
	},
	359: {
		n: 'Absol',
		m: 'Mega Absol',
	},
	362: {
		n: 'Glalie',
		m: 'Mega Glalie',
	},
	373: {
		n: 'Salamence',
		m: 'Mega Salamence',
	},
	376: {
		n: 'Metagross',
		m: 'Mega Metagross',
	},
	380: {
		n: 'Latias',
		m: 'Mega Latias',
	},
	381: {
		n: 'Latios',
		m: 'Mega Latios',
	},
	382: {
		n: 'Kyogre',
		primal: 'Primal Kyogre',
	},
	383: {
		n: 'Groudon',
		primal: 'Primal Groudon',
	},
	384: {
		n: 'Rayquaza',
		m: 'Mega Rayquaza',
	},
	386: {
		normal: 'Normal Forme Deoxys',
		attack: 'Attack Forme Deoxys',
		defense: 'Defense Forme Deoxys',
		speed: 'Speed Forme Deoxys',
	},
	412: {
		plant: 'Plant Cloak Burmy',
		sandy: 'Sandy Cloak Burmy',
		trash: 'Trash Cloak Burmy',
	},
	413: {
		plant: 'Plant Cloak Wormadam',
		sandy: 'Sandy Cloak Wormadam',
		trash: 'Trash Cloak Wormadam',
	},
	421: {
		overcast: 'Overcast Form Cherrim',
		sunshine: 'Sunshine Form Cherrim',
	},
	422: {
		east: 'East Sea Shellos',
		west: 'West Sea Shellos',
	},
	423: {
		east: 'East Sea Gastrodon',
		west: 'West Sea Gastrodon',
	},
	428: {
		n: 'Lopunny',
		m: 'Mega Lopunny',
	},
	445: {
		n: 'Garchomp',
		m: 'Mega Garchomp',
	},
	448: {
		n: 'Lucario',
		m: 'Mega Lucario',
	},
	460: {
		n: 'Abomasnow',
		m: 'Mega Abomasnow',
	},
	475: {
		n: 'Gallade',
		m: 'Mega Gallade',
	},
	479: {
		n: 'Rotom',
		fan: 'Fan Rotom',
		frost: 'Frost Rotom',
		heat: 'Heat Rotom',
		mow: 'Mow Rotom',
		wash: 'Wash Rotom',
	},
	487: {
		altered: 'Altered Forme Giratina',
		origin: 'Origin Forme Giratina',
	},
	492: {
		land: 'Land Forme Shaymin',
		sky: 'Sky Forme Shaymin',
	},
	493: {
		n: 'Normal Arceus',
		fire: 'Fire Arceus',
		water: 'Water Arceus',
		electric: 'Electric Arceus',
		grass: 'Grass Arceus',
		ice: 'Ice Arceus',
		fighting: 'Fighting Arceus',
		poison: 'Poison Arceus',
		ground: 'Ground Arceus',
		flying: 'Flying Arceus',
		psychic: 'Psychic Arceus',
		bug: 'Bug Arceus',
		rock: 'Rock Arceus',
		ghost: 'Ghost Arceus',
		dragon: 'Dragon Arceus',
		dark: 'Dark Arceus',
		steel: 'Steel Arceus',
		fairy: 'Fairy Arceus',
	},
	531: {
		n: 'Audino',
		m: 'Mega Audino',
	},
	550: {
		bluestripe: 'Blue Stripe Basculin',
		redstripe: 'Red Stripe Basculin'
	},
	555: {
		standard: 'Standard Mode Darmanitan',
		zen: 'Zen Mode Darmanitan',
	},
	585: {
		spring: 'Spring Form Deerling',
		summer: 'Summer Form Deerling',
		autumn: 'Autumn Form Deerling',
		winter: 'Winter Form Deerling',
	},
	586: {
		spring: 'Spring Form Sawbuck',
		summer: 'Summer Form Sawbuck',
		autumn: 'Autumn Form Sawbuck',
		winter: 'Winter Form Sawbuck',
	},
	641: {
		incarnate: 'Incarnate Forme Tornadus',
		therian: 'Therian Forme Tornadus',
	},
	642: {
		incarnate: 'Incarnate Forme Thundurus',
		therian: 'Therian Forme Thundurus',
	},
	645: {
		incarnate: 'Incarnate Forme Landorus',
		therian: 'Therian Forme Landorus',
	},
	646: {
		n: 'Kyurem',
		black: 'Black Kyurem',
		white: 'White Kyurem',
	},
	647: {
		ordinary: 'Ordinary Form Keldeo',
		resolute: 'Resolute Form Keldeo',
	},
	648: {
		aria: 'Aria Forme Meloetta',
		pirouette: 'Pirouette Forme Meloetta',
	},
	649: {
		n: 'Genesect',
		electric: 'Shock Drive Genesect',
		fire: 'Burn Drive Genesect',
		ice: 'Chill Drive Genesect',
		water: 'Douse Drive Genesect',
	},
	666: {
		meadow: 'Meadow Pattern Vivillon',
		archipelago: 'Archipelago Pattern Vivillon',
		continental: 'Continental Pattern Vivillon',
		elegant: 'Elegant Pattern Vivillon',
		fancy : 'Fancy Pattern Vivillon',
		garden: 'Garden Pattern Vivillon',
		highplains: 'High Plains Pattern Vivillon',
		icysnow: 'Icy Snow Pattern Vivillon',
		jungle: 'Jungle Pattern Vivillon',
		marine: 'Marine Pattern Vivillon',
		modern: 'Modern Pattern Vivillon',
		monsoon: 'Monsoon Pattern Vivillon',
		ocean: 'Ocean Pattern Vivillon',
		pokeball: 'Poké Ball Pattern Vivillon',
		polar: 'Polar Pattern Vivillon',
		river: 'River Pattern Vivillon',
		sandstorm: 'Sandstorm Pattern Vivillon',
		savanna: 'Savanna Pattern Vivillon',
		sun: 'Sun Pattern Vivillon',
		tundra: 'Tundra Pattern Vivillon',
	},
	669: {
		red: 'Red Flower Flabébé',
		yellow: 'Yellow Flower Flabébé',
		orange: 'Orange Flower Flabébé',
		blue: 'Blue Flower Flabébé',
		white: 'White Flower Flabébé',
	},
	670: {
		red: 'Red Flower Floette',
		yellow: 'Yellow Flower Floette',
		orange: 'Orange Flower Floette',
		blue: 'Blue Flower Floette',
		white: 'White Flower Floette',
		eternal: 'Eternal Flower Floette',
	},
	671: {
		red: 'Red Flower Florges',
		yellow: 'Yellow Flower Florges',
		orange: 'Orange Flower Florges',
		blue: 'Blue Flower Florges',
		white: 'White Flower Florges',
	},
	676: {
		natural: 'Natural Form Furfrou',
		dandy: 'Dandy Trim Furfrou',
		debutante: 'Debutante Trim Furfrou',
		diamond: 'Diamond Trim Furfrou',
		heart: 'Heart Trim Furfrou',
		kabuki: 'Kabuki Trim Furfrou',
		lareine: 'La Reine Trim Furfrou',
		matron: 'Matron Trim Furfrou',
		pharaoh: 'Pharaoh Trim Furfrou',
		star: 'Star Trim Furfrou',
	},
	681: {
		shield: 'Shield Forme Aegislash',
		blade: 'Blade Forme Aegislash',
	},
	710: {
		average: 'Average Size Pumpkaboo',
		small: 'Small Size Pumpkaboo',
		large: 'Large Size Pumpkaboo',
		super: 'Super Size Pumpkaboo',
	},
	711: {
		average: 'Average Size Gourgeist',
		small: 'Small Size Gourgeist',
		large: 'Large Size Gourgeist',
		super: 'Super Size Gourgeist',
	},
	716: {
		active: 'Active Mode Xerneas',
		neutral: 'Neutral Mode Xerneas',
	},
	719: {
		n: 'Diancie',
		m: 'Mega Diancie',
	},
	720: {
		confined: 'Hoopa Confined',
		unbound: 'Unbound Confined',
	},
}